import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import {Orbitron} from "next/font/google"

import { ThemeProvider } from "@/components/themeProvider";
const inter = Orbitron({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
      <div className="main">
          <div className="gradient" />
          </div>
          <main className="app ">
           
            {children}
          </main>
          </ThemeProvider>
        </body>
    </html>
  );
}
